language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: o6cRu7L7p6EAOq9dIliOyx+hgsVbU/bXB8INw5Is+oJ51g5pd8cRSsI9exK6yeSb4HjH1eSrEQKD980a6ilQ+oASIvrOsj1tX5R4diD+YmBKsx79Uv21L5Y4MsDU9cXYKKjPARdpppu+QqzQOHiISCjf7LcqGBDI3HOrkSavvl+7q2bWxwB8PhGS8Ru2Lth9wjf1VL6NgcFJcsmDw+3nZ4PEc3lCLM4nJDssZt3o1M1dv7q/HacDR5mN6EsnLS6Cpc7gTvYK/7Udb6tI2ks/OGuTWEc9QdJ3BCWz6nMiFfttR0YEbtsHaVO4M2VbyeSOA69o1yUX+8TG/wcuIVHEXibjgxrwyfyhLnEhf0nQ3Y8MdqUt84nezPUikf6Bcdbl3XDqFBl2EbCsscrYc0ovECsb7Wfh6iwB9UoKR1fF7yuon6gz7lvmsQvH4ijS8yIsira8nGVn4X2Bdn8KPt60aif3kUb5ocElte1LvwWnP4ZiNThlZrGYnAf6kddVzY6E8zmayLK3DfEJ4xUtQKL0VT3j6rYoNe2SUsH9jPYleaJ6iL8Ll4jryqESSbxY1kmnSycNQKksEfY1UCVDPs51Ey4aSuMY5PdIMZFfMnOoHREEqvcO8sBGKMnbHewPliGHxFVKoQG8JsGuuG1gQI/aAEoBYffn575fUJ/RhDIVFzU=
  app: droned-reviews
  on:
    repo: Schmerb/droned-reviews
